name: protein_regression
channels:
  - apple
  - conda-forge
dependencies:
  - appnope=0.1.3
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - attrs=21.4.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.1
  - bleach=5.0.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.6.15
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cffi=1.15.0
  - debugpy=1.6.0
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - et_xmlfile=1.0.1
  - executing=0.8.3
  - flit-core=3.7.1
  - hdf5=1.12.1
  - importlib_resources=5.7.1
  - ipykernel=6.13.0
  - ipython=8.3.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.7.0
  - jedi=0.18.1
  - jinja2=3.1.1
  - json5=0.9.5
  - jsonschema=4.4.0
  - jupyter=1.0.0
  - jupyter_client=7.3.0
  - jupyter_console=6.4.3
  - jupyter_core=4.9.2
  - jupyterlab=2.1.0
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=1.0.9
  - jupyterlab_widgets=1.1.0
  - krb5=1.19.3
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.83.0
  - libcxx=13.0.1
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgfortran=5.0.0.dev0
  - libgfortran5=11.0.1.dev0
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - libnghttp2=1.47.0
  - libopenblas=0.3.20
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libzlib=1.2.11
  - llvm-openmp=14.0.3
  - llvmlite=0.38.0
  - matplotlib-inline=0.1.3
  - mistune=0.8.4
  - nbclient=0.5.13
  - nbconvert=6.4.5
  - nbformat=5.4.0
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - notebook=6.4.11
  - numba=0.55.1
  - numpy=1.21.6
  - openpyxl=3.0.9
  - openssl=3.0.4
  - packaging=21.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=22.0.4
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.29
  - prompt_toolkit=3.0.29
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.12.0
  - pyparsing=3.0.8
  - pyrsistent=0.18.1
  - python=3.9.12
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.15.3
  - python_abi=3.9
  - pyzmq=22.3.0
  - readline=8.1
  - send2trash=1.8.0
  - soupsieve=2.3.1
  - sqlite=3.38.4
  - stack_data=0.2.0
  - tensorflow-deps=2.8.0
  - terminado=0.13.3
  - testpath=0.6.0
  - tk=8.6.12
  - tornado=6.1
  - traitlets=5.1.1
  - tzdata=2022a
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - widgetsnbextension=3.6.0
  - xz=5.2.5
  - zeromq=4.3.4
  - zlib=1.2.11
  - pip:
    - absl-py==1.4.0
    - alembic==1.7.7
    - astunparse==1.6.3
    - biopython==1.79
    - cachetools==5.3.0
    - certifi==2022.12.7
    - charset-normalizer==3.1.0
    - click==8.1.3
    - cloudpickle==2.2.1
    - cycler==0.11.0
    - databricks-cli==0.16.6
    - deprecated==1.2.13
    - dm-tree==0.1.8
    - docker==5.0.3
    - filelock==3.12.0
    - flask==2.1.2
    - flatbuffers==23.3.3
    - fonttools==4.33.3
    - gast==0.5.3
    - gitdb==4.0.9
    - gitpython==3.1.27
    - gmr==1.6.2
    - google-auth==2.17.2
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - gpflow==2.5.1
    - grpcio==1.53.0
    - gunicorn==20.1.0
    - h5py==3.8.0
    - idna==3.4
    - imageio==2.19.3
    - importlib-metadata==6.3.0
    - iniconfig==1.1.1
    - itsdangerous==2.1.2
    - joblib==1.1.0
    - keras==2.8.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.4.2
    - lark==1.1.2
    - libclang==16.0.0
    - mako==1.2.0
    - markdown==3.4.3
    - markupsafe==2.1.2
    - matplotlib==3.5.2
    - mlflow==1.25.1
    - mpmath==1.3.0
    - multipledispatch==0.6.0
    - networkx==3.1
    - oauthlib==3.2.2
    - opt-einsum==3.3.0
    - pandas==1.4.2
    - pillow==9.1.0
    - pip-autoremove==0.10.0
    - pluggy==1.0.0
    - prometheus-flask-exporter==0.20.1
    - protobuf==3.20.0
    - py==1.11.0
    - pyaml==21.10.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyjwt==2.3.0
    - pynndescent==0.5.6
    - pytest==7.1.2
    - pytz==2022.1
    - pyyaml==6.0
    - qtconsole==5.4.2
    - qtpy==2.3.1
    - querystring-parser==1.2.4
    - requests==2.28.2
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - scikit-learn==1.0.2
    - scikit-optimize==0.9.0
    - scipy==1.8.0
    - seaborn==0.11.2
    - setuptools==67.6.1
    - shapely==1.8.2
    - six==1.15.0
    - smmap==5.0.0
    - sqlalchemy==1.4.36
    - sqlparse==0.4.2
    - sympy==1.12
    - tabulate==0.8.9
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow-macos==2.8.0
    - tensorflow-metal==0.4.0
    - tensorflow-probability==0.16.0
    - termcolor==2.2.0
    - tf-estimator-nightly==2.8.0.dev2021122109
    - threadpoolctl==3.1.0
    - tomli==2.0.1
    - torch==2.0.1
    - torch-geometric==2.3.1
    - torch-sparse==0.6.17
    - tqdm==4.64.0
    - typing-extensions==4.5.0
    - umap-learn==0.5.3
    - urllib3==1.26.15
    - websocket-client==1.3.2
    - werkzeug==2.2.3
    - wheel==0.40.0
    - wrapt==1.15.0
    - zipp==3.15.0
