EXPERIMENT_TYPE = "EXPERIMENT_TYPE"
REGRESSION = "REGRESSION"
OPTIMIZATION = "OPTIMIZATION"
DATASET = "DATASET"
REPRESENTATION = "REPRESENTATION"
METHOD = "METHOD"
SPLIT = "SPLIT"
SEED = "SEED"

# metrics
MSE = "MSE"
MedSE = "MedSE"
SEVar = "SEVar"
MLL = "MLL"
SPEARMAN_RHO = "rho"

# representations
ONE_HOT = "one_hot"
TRANSFORMER = "transformer"
VAE = "vae"
NONSENSE = "nonsense"
KNN_name = 'knn'

# optimization
OBSERVED_Y = "OBSERVED_Y"
